// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: sacerdote.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Habitante struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Habitante) Reset() {
	*x = Habitante{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sacerdote_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Habitante) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Habitante) ProtoMessage() {}

func (x *Habitante) ProtoReflect() protoreflect.Message {
	mi := &file_sacerdote_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Habitante.ProtoReflect.Descriptor instead.
func (*Habitante) Descriptor() ([]byte, []int) {
	return file_sacerdote_proto_rawDescGZIP(), []int{0}
}

func (x *Habitante) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PedidoTransacao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClienteId string `protobuf:"bytes,1,opt,name=clienteId,proto3" json:"clienteId,omitempty"`
	Tipo      string `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Valor     int64  `protobuf:"varint,3,opt,name=valor,proto3" json:"valor,omitempty"`
	Descricao string `protobuf:"bytes,4,opt,name=descricao,proto3" json:"descricao,omitempty"`
}

func (x *PedidoTransacao) Reset() {
	*x = PedidoTransacao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sacerdote_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PedidoTransacao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PedidoTransacao) ProtoMessage() {}

func (x *PedidoTransacao) ProtoReflect() protoreflect.Message {
	mi := &file_sacerdote_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PedidoTransacao.ProtoReflect.Descriptor instead.
func (*PedidoTransacao) Descriptor() ([]byte, []int) {
	return file_sacerdote_proto_rawDescGZIP(), []int{1}
}

func (x *PedidoTransacao) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

func (x *PedidoTransacao) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *PedidoTransacao) GetValor() int64 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *PedidoTransacao) GetDescricao() string {
	if x != nil {
		return x.Descricao
	}
	return ""
}

type ResultadoTransacao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NovoSaldo int64 `protobuf:"varint,1,opt,name=novoSaldo,proto3" json:"novoSaldo,omitempty"`
	Limite    int64 `protobuf:"varint,2,opt,name=limite,proto3" json:"limite,omitempty"`
	Erro      int32 `protobuf:"varint,3,opt,name=erro,proto3" json:"erro,omitempty"`
}

func (x *ResultadoTransacao) Reset() {
	*x = ResultadoTransacao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sacerdote_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultadoTransacao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoTransacao) ProtoMessage() {}

func (x *ResultadoTransacao) ProtoReflect() protoreflect.Message {
	mi := &file_sacerdote_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoTransacao.ProtoReflect.Descriptor instead.
func (*ResultadoTransacao) Descriptor() ([]byte, []int) {
	return file_sacerdote_proto_rawDescGZIP(), []int{2}
}

func (x *ResultadoTransacao) GetNovoSaldo() int64 {
	if x != nil {
		return x.NovoSaldo
	}
	return 0
}

func (x *ResultadoTransacao) GetLimite() int64 {
	if x != nil {
		return x.Limite
	}
	return 0
}

func (x *ResultadoTransacao) GetErro() int32 {
	if x != nil {
		return x.Erro
	}
	return 0
}

type Transacao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tipo        string                 `protobuf:"bytes,1,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Valor       int64                  `protobuf:"varint,2,opt,name=valor,proto3" json:"valor,omitempty"`
	RealizadaEm *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=realizadaEm,proto3" json:"realizadaEm,omitempty"`
	Descricao   string                 `protobuf:"bytes,4,opt,name=descricao,proto3" json:"descricao,omitempty"`
}

func (x *Transacao) Reset() {
	*x = Transacao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sacerdote_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transacao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transacao) ProtoMessage() {}

func (x *Transacao) ProtoReflect() protoreflect.Message {
	mi := &file_sacerdote_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transacao.ProtoReflect.Descriptor instead.
func (*Transacao) Descriptor() ([]byte, []int) {
	return file_sacerdote_proto_rawDescGZIP(), []int{3}
}

func (x *Transacao) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Transacao) GetValor() int64 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *Transacao) GetRealizadaEm() *timestamppb.Timestamp {
	if x != nil {
		return x.RealizadaEm
	}
	return nil
}

func (x *Transacao) GetDescricao() string {
	if x != nil {
		return x.Descricao
	}
	return ""
}

type Extrato struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Saldo             int64        `protobuf:"varint,1,opt,name=saldo,proto3" json:"saldo,omitempty"`
	Limite            int64        `protobuf:"varint,2,opt,name=limite,proto3" json:"limite,omitempty"`
	UltimasTransacoes []*Transacao `protobuf:"bytes,3,rep,name=ultimas_transacoes,json=ultimasTransacoes,proto3" json:"ultimas_transacoes,omitempty"`
}

func (x *Extrato) Reset() {
	*x = Extrato{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sacerdote_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Extrato) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extrato) ProtoMessage() {}

func (x *Extrato) ProtoReflect() protoreflect.Message {
	mi := &file_sacerdote_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extrato.ProtoReflect.Descriptor instead.
func (*Extrato) Descriptor() ([]byte, []int) {
	return file_sacerdote_proto_rawDescGZIP(), []int{4}
}

func (x *Extrato) GetSaldo() int64 {
	if x != nil {
		return x.Saldo
	}
	return 0
}

func (x *Extrato) GetLimite() int64 {
	if x != nil {
		return x.Limite
	}
	return 0
}

func (x *Extrato) GetUltimasTransacoes() []*Transacao {
	if x != nil {
		return x.UltimasTransacoes
	}
	return nil
}

var File_sacerdote_proto protoreflect.FileDescriptor

var file_sacerdote_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x61, 0x63, 0x65, 0x72, 0x64, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x1b, 0x0a, 0x09, 0x48, 0x61, 0x62, 0x69, 0x74, 0x61, 0x6e, 0x74, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x77, 0x0a, 0x0f, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x61, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x69, 0x70, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x63, 0x61, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x63, 0x61, 0x6f, 0x22, 0x5e, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x61, 0x64, 0x6f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x61, 0x6f, 0x12, 0x1c,
	0x0a, 0x09, 0x6e, 0x6f, 0x76, 0x6f, 0x53, 0x61, 0x6c, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x6e, 0x6f, 0x76, 0x6f, 0x53, 0x61, 0x6c, 0x64, 0x6f, 0x12, 0x16, 0x0a, 0x06,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x72, 0x72, 0x6f, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x65, 0x72, 0x72, 0x6f, 0x22, 0x91, 0x01, 0x0a, 0x09, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x61, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72,
	0x12, 0x3c, 0x0a, 0x0b, 0x72, 0x65, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64, 0x61, 0x45, 0x6d, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x0b, 0x72, 0x65, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64, 0x61, 0x45, 0x6d, 0x12, 0x1c,
	0x0a, 0x09, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x63, 0x61, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x63, 0x61, 0x6f, 0x22, 0x72, 0x0a, 0x07,
	0x45, 0x78, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x61, 0x6c, 0x64, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x61, 0x6c, 0x64, 0x6f, 0x12, 0x16, 0x0a,
	0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x65, 0x12, 0x39, 0x0a, 0x12, 0x75, 0x6c, 0x74, 0x69, 0x6d, 0x61, 0x73,
	0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x6f, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x61, 0x6f, 0x52, 0x11, 0x75,
	0x6c, 0x74, 0x69, 0x6d, 0x61, 0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x6f, 0x65, 0x73,
	0x32, 0x76, 0x0a, 0x09, 0x53, 0x61, 0x63, 0x65, 0x72, 0x64, 0x6f, 0x74, 0x65, 0x12, 0x3d, 0x0a,
	0x12, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x61, 0x6f, 0x12, 0x10, 0x2e, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x61, 0x6f, 0x1a, 0x13, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x64,
	0x6f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x61, 0x6f, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x10,
	0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x72, 0x45, 0x78, 0x74, 0x72, 0x61, 0x74, 0x6f,
	0x12, 0x0a, 0x2e, 0x48, 0x61, 0x62, 0x69, 0x74, 0x61, 0x6e, 0x74, 0x65, 0x1a, 0x08, 0x2e, 0x45,
	0x78, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sacerdote_proto_rawDescOnce sync.Once
	file_sacerdote_proto_rawDescData = file_sacerdote_proto_rawDesc
)

func file_sacerdote_proto_rawDescGZIP() []byte {
	file_sacerdote_proto_rawDescOnce.Do(func() {
		file_sacerdote_proto_rawDescData = protoimpl.X.CompressGZIP(file_sacerdote_proto_rawDescData)
	})
	return file_sacerdote_proto_rawDescData
}

var file_sacerdote_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sacerdote_proto_goTypes = []interface{}{
	(*Habitante)(nil),             // 0: Habitante
	(*PedidoTransacao)(nil),       // 1: PedidoTransacao
	(*ResultadoTransacao)(nil),    // 2: ResultadoTransacao
	(*Transacao)(nil),             // 3: Transacao
	(*Extrato)(nil),               // 4: Extrato
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_sacerdote_proto_depIdxs = []int32{
	5, // 0: Transacao.realizadaEm:type_name -> google.protobuf.Timestamp
	3, // 1: Extrato.ultimas_transacoes:type_name -> Transacao
	1, // 2: Sacerdote.RegistrarTransacao:input_type -> PedidoTransacao
	0, // 3: Sacerdote.ConsultarExtrato:input_type -> Habitante
	2, // 4: Sacerdote.RegistrarTransacao:output_type -> ResultadoTransacao
	4, // 5: Sacerdote.ConsultarExtrato:output_type -> Extrato
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sacerdote_proto_init() }
func file_sacerdote_proto_init() {
	if File_sacerdote_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sacerdote_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Habitante); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sacerdote_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PedidoTransacao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sacerdote_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultadoTransacao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sacerdote_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transacao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sacerdote_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Extrato); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sacerdote_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sacerdote_proto_goTypes,
		DependencyIndexes: file_sacerdote_proto_depIdxs,
		MessageInfos:      file_sacerdote_proto_msgTypes,
	}.Build()
	File_sacerdote_proto = out.File
	file_sacerdote_proto_rawDesc = nil
	file_sacerdote_proto_goTypes = nil
	file_sacerdote_proto_depIdxs = nil
}
