// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: sacerdote.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Habitante struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Habitante) Reset() {
	*x = Habitante{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sacerdote_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Habitante) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Habitante) ProtoMessage() {}

func (x *Habitante) ProtoReflect() protoreflect.Message {
	mi := &file_sacerdote_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Habitante.ProtoReflect.Descriptor instead.
func (*Habitante) Descriptor() ([]byte, []int) {
	return file_sacerdote_proto_rawDescGZIP(), []int{0}
}

func (x *Habitante) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ConsultaStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error bool `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ConsultaStatus) Reset() {
	*x = ConsultaStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sacerdote_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsultaStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultaStatus) ProtoMessage() {}

func (x *ConsultaStatus) ProtoReflect() protoreflect.Message {
	mi := &file_sacerdote_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultaStatus.ProtoReflect.Descriptor instead.
func (*ConsultaStatus) Descriptor() ([]byte, []int) {
	return file_sacerdote_proto_rawDescGZIP(), []int{1}
}

func (x *ConsultaStatus) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

type SaidaStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error bool `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *SaidaStatus) Reset() {
	*x = SaidaStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sacerdote_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaidaStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaidaStatus) ProtoMessage() {}

func (x *SaidaStatus) ProtoReflect() protoreflect.Message {
	mi := &file_sacerdote_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaidaStatus.ProtoReflect.Descriptor instead.
func (*SaidaStatus) Descriptor() ([]byte, []int) {
	return file_sacerdote_proto_rawDescGZIP(), []int{2}
}

func (x *SaidaStatus) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

type Transacao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tipo        string                 `protobuf:"bytes,1,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Valor       int64                  `protobuf:"varint,2,opt,name=valor,proto3" json:"valor,omitempty"`
	RealizadaEm *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=realizadaEm,proto3" json:"realizadaEm,omitempty"`
	Descricao   string                 `protobuf:"bytes,4,opt,name=descricao,proto3" json:"descricao,omitempty"`
}

func (x *Transacao) Reset() {
	*x = Transacao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sacerdote_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transacao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transacao) ProtoMessage() {}

func (x *Transacao) ProtoReflect() protoreflect.Message {
	mi := &file_sacerdote_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transacao.ProtoReflect.Descriptor instead.
func (*Transacao) Descriptor() ([]byte, []int) {
	return file_sacerdote_proto_rawDescGZIP(), []int{3}
}

func (x *Transacao) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Transacao) GetValor() int64 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *Transacao) GetRealizadaEm() *timestamppb.Timestamp {
	if x != nil {
		return x.RealizadaEm
	}
	return nil
}

func (x *Transacao) GetDescricao() string {
	if x != nil {
		return x.Descricao
	}
	return ""
}

type Extrato struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Saldo             int64        `protobuf:"varint,1,opt,name=saldo,proto3" json:"saldo,omitempty"`
	Limite            int64        `protobuf:"varint,2,opt,name=limite,proto3" json:"limite,omitempty"`
	UltimasTransacoes []*Transacao `protobuf:"bytes,3,rep,name=ultimas_transacoes,json=ultimasTransacoes,proto3" json:"ultimas_transacoes,omitempty"`
}

func (x *Extrato) Reset() {
	*x = Extrato{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sacerdote_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Extrato) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extrato) ProtoMessage() {}

func (x *Extrato) ProtoReflect() protoreflect.Message {
	mi := &file_sacerdote_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extrato.ProtoReflect.Descriptor instead.
func (*Extrato) Descriptor() ([]byte, []int) {
	return file_sacerdote_proto_rawDescGZIP(), []int{4}
}

func (x *Extrato) GetSaldo() int64 {
	if x != nil {
		return x.Saldo
	}
	return 0
}

func (x *Extrato) GetLimite() int64 {
	if x != nil {
		return x.Limite
	}
	return 0
}

func (x *Extrato) GetUltimasTransacoes() []*Transacao {
	if x != nil {
		return x.UltimasTransacoes
	}
	return nil
}

type SaldoConsulta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClienteId string `protobuf:"bytes,1,opt,name=clienteId,proto3" json:"clienteId,omitempty"`
}

func (x *SaldoConsulta) Reset() {
	*x = SaldoConsulta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sacerdote_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaldoConsulta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaldoConsulta) ProtoMessage() {}

func (x *SaldoConsulta) ProtoReflect() protoreflect.Message {
	mi := &file_sacerdote_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaldoConsulta.ProtoReflect.Descriptor instead.
func (*SaldoConsulta) Descriptor() ([]byte, []int) {
	return file_sacerdote_proto_rawDescGZIP(), []int{5}
}

func (x *SaldoConsulta) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

type SaldoAtualizacao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClienteId string `protobuf:"bytes,1,opt,name=clienteId,proto3" json:"clienteId,omitempty"`
	Motivo    string `protobuf:"bytes,2,opt,name=motivo,proto3" json:"motivo,omitempty"`
	NovoSaldo int64  `protobuf:"varint,3,opt,name=novoSaldo,proto3" json:"novoSaldo,omitempty"`
}

func (x *SaldoAtualizacao) Reset() {
	*x = SaldoAtualizacao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sacerdote_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaldoAtualizacao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaldoAtualizacao) ProtoMessage() {}

func (x *SaldoAtualizacao) ProtoReflect() protoreflect.Message {
	mi := &file_sacerdote_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaldoAtualizacao.ProtoReflect.Descriptor instead.
func (*SaldoAtualizacao) Descriptor() ([]byte, []int) {
	return file_sacerdote_proto_rawDescGZIP(), []int{6}
}

func (x *SaldoAtualizacao) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

func (x *SaldoAtualizacao) GetMotivo() string {
	if x != nil {
		return x.Motivo
	}
	return ""
}

func (x *SaldoAtualizacao) GetNovoSaldo() int64 {
	if x != nil {
		return x.NovoSaldo
	}
	return 0
}

type SaldoCliente struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Saldo  int64 `protobuf:"varint,1,opt,name=saldo,proto3" json:"saldo,omitempty"`
	Limite int64 `protobuf:"varint,2,opt,name=limite,proto3" json:"limite,omitempty"`
}

func (x *SaldoCliente) Reset() {
	*x = SaldoCliente{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sacerdote_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaldoCliente) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaldoCliente) ProtoMessage() {}

func (x *SaldoCliente) ProtoReflect() protoreflect.Message {
	mi := &file_sacerdote_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaldoCliente.ProtoReflect.Descriptor instead.
func (*SaldoCliente) Descriptor() ([]byte, []int) {
	return file_sacerdote_proto_rawDescGZIP(), []int{7}
}

func (x *SaldoCliente) GetSaldo() int64 {
	if x != nil {
		return x.Saldo
	}
	return 0
}

func (x *SaldoCliente) GetLimite() int64 {
	if x != nil {
		return x.Limite
	}
	return 0
}

var File_sacerdote_proto protoreflect.FileDescriptor

var file_sacerdote_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x61, 0x63, 0x65, 0x72, 0x64, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x1b, 0x0a, 0x09, 0x48, 0x61, 0x62, 0x69, 0x74, 0x61, 0x6e, 0x74, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x26, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x23, 0x0a, 0x0b, 0x53, 0x61, 0x69, 0x64, 0x61,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x91, 0x01, 0x0a,
	0x09, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x61, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69,
	0x70, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x6f, 0x72, 0x12, 0x3c, 0x0a, 0x0b, 0x72, 0x65, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64,
	0x61, 0x45, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x72, 0x65, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64, 0x61,
	0x45, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x63, 0x61, 0x6f, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x63, 0x61, 0x6f,
	0x22, 0x72, 0x0a, 0x07, 0x45, 0x78, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x61, 0x6c, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x61, 0x6c, 0x64,
	0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x12, 0x39, 0x0a, 0x12, 0x75, 0x6c, 0x74,
	0x69, 0x6d, 0x61, 0x73, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x6f, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x61,
	0x6f, 0x52, 0x11, 0x75, 0x6c, 0x74, 0x69, 0x6d, 0x61, 0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x6f, 0x65, 0x73, 0x22, 0x2d, 0x0a, 0x0d, 0x53, 0x61, 0x6c, 0x64, 0x6f, 0x43, 0x6f, 0x6e,
	0x73, 0x75, 0x6c, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x65, 0x49, 0x64, 0x22, 0x66, 0x0a, 0x10, 0x53, 0x61, 0x6c, 0x64, 0x6f, 0x41, 0x74, 0x75, 0x61,
	0x6c, 0x69, 0x7a, 0x61, 0x63, 0x61, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x74, 0x69, 0x76, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x74, 0x69, 0x76, 0x6f, 0x12, 0x1c, 0x0a,
	0x09, 0x6e, 0x6f, 0x76, 0x6f, 0x53, 0x61, 0x6c, 0x64, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x6e, 0x6f, 0x76, 0x6f, 0x53, 0x61, 0x6c, 0x64, 0x6f, 0x22, 0x3c, 0x0a, 0x0c, 0x53,
	0x61, 0x6c, 0x64, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x61, 0x6c, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x61, 0x6c, 0x64,
	0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x32, 0xec, 0x01, 0x0a, 0x09, 0x53, 0x61,
	0x63, 0x65, 0x72, 0x64, 0x6f, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x73, 0x75,
	0x6c, 0x74, 0x61, 0x72, 0x12, 0x0a, 0x2e, 0x48, 0x61, 0x62, 0x69, 0x74, 0x61, 0x6e, 0x74, 0x65,
	0x1a, 0x0f, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x00, 0x12, 0x22, 0x0a, 0x04, 0x53, 0x61, 0x69, 0x72, 0x12, 0x0a, 0x2e, 0x48, 0x61,
	0x62, 0x69, 0x74, 0x61, 0x6e, 0x74, 0x65, 0x1a, 0x0c, 0x2e, 0x53, 0x61, 0x69, 0x64, 0x61, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x73, 0x75,
	0x6c, 0x74, 0x61, 0x72, 0x53, 0x61, 0x6c, 0x64, 0x6f, 0x12, 0x0e, 0x2e, 0x53, 0x61, 0x6c, 0x64,
	0x6f, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x1a, 0x0d, 0x2e, 0x53, 0x61, 0x6c, 0x64,
	0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x0a, 0x4d, 0x75,
	0x64, 0x61, 0x72, 0x53, 0x61, 0x6c, 0x64, 0x6f, 0x12, 0x11, 0x2e, 0x53, 0x61, 0x6c, 0x64, 0x6f,
	0x41, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x63, 0x61, 0x6f, 0x1a, 0x0d, 0x2e, 0x53, 0x61,
	0x6c, 0x64, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x10,
	0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x72, 0x45, 0x78, 0x74, 0x72, 0x61, 0x74, 0x6f,
	0x12, 0x0a, 0x2e, 0x48, 0x61, 0x62, 0x69, 0x74, 0x61, 0x6e, 0x74, 0x65, 0x1a, 0x08, 0x2e, 0x45,
	0x78, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sacerdote_proto_rawDescOnce sync.Once
	file_sacerdote_proto_rawDescData = file_sacerdote_proto_rawDesc
)

func file_sacerdote_proto_rawDescGZIP() []byte {
	file_sacerdote_proto_rawDescOnce.Do(func() {
		file_sacerdote_proto_rawDescData = protoimpl.X.CompressGZIP(file_sacerdote_proto_rawDescData)
	})
	return file_sacerdote_proto_rawDescData
}

var file_sacerdote_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sacerdote_proto_goTypes = []interface{}{
	(*Habitante)(nil),             // 0: Habitante
	(*ConsultaStatus)(nil),        // 1: ConsultaStatus
	(*SaidaStatus)(nil),           // 2: SaidaStatus
	(*Transacao)(nil),             // 3: Transacao
	(*Extrato)(nil),               // 4: Extrato
	(*SaldoConsulta)(nil),         // 5: SaldoConsulta
	(*SaldoAtualizacao)(nil),      // 6: SaldoAtualizacao
	(*SaldoCliente)(nil),          // 7: SaldoCliente
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_sacerdote_proto_depIdxs = []int32{
	8, // 0: Transacao.realizadaEm:type_name -> google.protobuf.Timestamp
	3, // 1: Extrato.ultimas_transacoes:type_name -> Transacao
	0, // 2: Sacerdote.Consultar:input_type -> Habitante
	0, // 3: Sacerdote.Sair:input_type -> Habitante
	5, // 4: Sacerdote.ConsultarSaldo:input_type -> SaldoConsulta
	6, // 5: Sacerdote.MudarSaldo:input_type -> SaldoAtualizacao
	0, // 6: Sacerdote.ConsultarExtrato:input_type -> Habitante
	1, // 7: Sacerdote.Consultar:output_type -> ConsultaStatus
	2, // 8: Sacerdote.Sair:output_type -> SaidaStatus
	7, // 9: Sacerdote.ConsultarSaldo:output_type -> SaldoCliente
	7, // 10: Sacerdote.MudarSaldo:output_type -> SaldoCliente
	4, // 11: Sacerdote.ConsultarExtrato:output_type -> Extrato
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sacerdote_proto_init() }
func file_sacerdote_proto_init() {
	if File_sacerdote_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sacerdote_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Habitante); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sacerdote_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsultaStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sacerdote_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaidaStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sacerdote_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transacao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sacerdote_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Extrato); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sacerdote_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaldoConsulta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sacerdote_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaldoAtualizacao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sacerdote_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaldoCliente); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sacerdote_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sacerdote_proto_goTypes,
		DependencyIndexes: file_sacerdote_proto_depIdxs,
		MessageInfos:      file_sacerdote_proto_msgTypes,
	}.Build()
	File_sacerdote_proto = out.File
	file_sacerdote_proto_rawDesc = nil
	file_sacerdote_proto_goTypes = nil
	file_sacerdote_proto_depIdxs = nil
}
